//Values below are just for initialising and will be changed when synth is initialised to current panel controls & EEPROM settings
byte midiChannel = MIDI_CHANNEL_OMNI;//(EEPROM)
String patchName = INITPATCHNAME;
boolean encCW = true;//This is to set the encoder to increment when turned CW - Settings Option

// polykit parameters in order of mux

float pwLFO = 0;
float pwLFOstr = 0; // for display
float fmDepth = 0;
float fmDepthstr = 0;
float osc2PW = 0;
float osc2PWstr = 0;
float osc2PWM = 0;
float osc2PWMstr = 0;
float osc1PW = 0;
float osc1PWstr = 0;
float osc1PWM = 0;
float osc1PWMstr = 0;
float osc1Range = 0;
float osc1Rangestr = 0;
float oct1A = 0;
float oct1B = 0;
float osc2Range = 0;
float osc2Rangestr = 0;
float oct2A = 0;
float oct2B = 0;
float stack = 0;
float stackstr = 0;
float glideTime = 0;
float glideTimestr = 0;
float osc2Detune = 0;
float osc2Detunestr = 0;
float noiseLevel = 0;
float noiseLevelstr = 0; // for display
float osc2SawLevelstr = 0; //for display
float osc2SawLevel = 0;
float osc1SawLevel = 0; // for display
float osc1SawLevelstr = 0;
float osc2PulseLevel = 0;
float osc2PulseLevelstr = 0; // for display
float osc1PulseLevel = 0;
float osc1PulseLevelstr = 0; // for display

float filterCutoff = 0;
float oldfilterCutoff = 0;
float filterCutoffstr = 0; // for display
float filterLFO = 0;
float filterLFOstr = 0; // for display
float filterRes = 0;
float filterResstr = 0;
float filterType = 0;
float filterA = 0;
float filterB = 0;
float filterC = 0;
float filterEGlevel = 0;
float filterEGlevelstr = 0;
float LFORate = 0;
float LFORatestr = 0; //for display
String StratusLFOWaveform = "                ";
float LFOWaveform = 0;
float filterAttack = 0;
float filterAttackstr = 0;
float filterDecay = 0;
float filterDecaystr = 0;
float filterSustain = 0;
float filterSustainstr = 0;
float filterRelease = 0;
float filterReleasestr = 0;
float ampAttack = 0;
float oldampAttack = 0;
float ampAttackstr = 0;
float ampDecay = 0;
float oldampDecay = 0;
float ampDecaystr = 0;
float ampSustain = 0;
float oldampSustain = 0;
float ampSustainstr = 0;
float ampRelease = 0;
float oldampRelease = 0;
float ampReleasestr = 0;
float volumeControl = 0;
float volumeControlstr = 0; // for display

int glideSW = 0;
int keytrack = 0;
int vcaLoop = 0;
int vcaVel = 0;
int vcaGate = 0;
int chorus1 = 0;
int chorus2 = 0;
int lfoAlt = 0;
int monoMulti = 0;
int filterPoleSW = 0;
int filterVel = 0;
int filterLoop = 0;
int filterEGinv = 0;
int PitchBendLevel = 0;
int PitchBendLevelstr = 0; // for display
int modWheelDepth = 0;
float modWheelLevel = 0;
float modWheelLevelstr = 0;
int filterLogLin = 0;
int ampLogLin = 0;
int linLog = 0;
float afterTouch = 0;
int AfterTouchDest = 0;

int returnvalue = 0;
